[package]
name = "new_auto_updater"
version = "0.1.0"
authors = ["amk91 <agostino.pisanelli@gmail.com>"]

[dependencies]
zip = "0.4"
walkdir = "2"
chrono = "0.4.6"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[features]
dev = []